# Docker Compose configuration optimized for Coolify deployment
# This version addresses common mounting and directory structure issues

version: '3.8'

services:
  smart-traffic-ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart-traffic-ai-system
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - SYSTEM_MODE=production
      - DATABASE_PATH=/app/data/traffic_system.db
      - LOG_LEVEL=INFO
      - LOG_DIR=/app/logs
      - LOG_RETENTION=30days
      - LOG_MAX_SIZE=50MB
      - LOG_ENABLE_JSON=true
      - LOG_ENABLE_PERFORMANCE=true
      - REDIS_URL=redis://redis:6379
      - MQTT_BROKER_HOST=mosquitto
      - MQTT_BROKER_PORT=1883
    volumes:
      - traffic_data:/app/data
      - traffic_logs:/app/logs
      - traffic_models:/app/models
    depends_on:
      redis:
        condition: service_healthy
      mosquitto:
        condition: service_healthy
    networks:
      - traffic_network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

  redis:
    image: redis:7-alpine
    container_name: traffic-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - traffic_network
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: traffic-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
      - mosquitto_config:/mosquitto/config
    configs:
      - source: mosquitto_conf
        target: /mosquitto/config/mosquitto.conf
    networks:
      - traffic_network
    healthcheck:
      test: ["CMD", "timeout", "5", "nc", "-z", "localhost", "1883"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

configs:
  mosquitto_conf:
    file: ./config/mosquitto.conf

volumes:
  traffic_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
  traffic_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./logs
  traffic_models:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./models
  redis_data:
    driver: local
  mosquitto_data:
    driver: local
  mosquitto_logs:
    driver: local
  mosquitto_config:
    driver: local

networks:
  traffic_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
