version: '3.8'

services:
  smart-traffic-ai:
    build: .
    container_name: smart-traffic-ai-system
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - SYSTEM_MODE=production
      - DATABASE_PATH=/app/data/traffic_system.db
      - LOG_LEVEL=INFO
      - REDIS_URL=redis://redis:6379
      - MQTT_BROKER_HOST=mosquitto
      - MQTT_BROKER_PORT=1883
    volumes:
      - traffic_data:/app/data
      - traffic_logs:/app/logs
      - traffic_models:/app/models
    depends_on:
      - redis
      - mosquitto
    networks:
      - traffic_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  redis:
    image: redis:7-alpine
    container_name: traffic-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - traffic_network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: traffic-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - traffic_network
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-t", "test", "-m", "test"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  traffic_data:
    driver: local
  traffic_logs:
    driver: local
  traffic_models:
    driver: local
  redis_data:
    driver: local
  mosquitto_data:
    driver: local
  mosquitto_logs:
    driver: local

networks:
  traffic_network:
    driver: bridge
